package controllers;

import utils.FileWriter;

public class RegisterController {
	private String filePath;
	private String allText;

	/**
	 * 
	 * @param filePath
	 *            , URL-address of target folder.
	 */

	public RegisterController(String filePath) {
		this.filePath = filePath;
	}

	/**
	 * Changes the format of the strings and also writes the latest return value
	 * to file along with all previous values generated by this class instance.
	 * 
	 * 
	 * @param resText
	 *            , String representation of text contained within the
	 *            resultfield of the GUI.
	 * @param startNr
	 *            , String representation of the start number of the participant
	 *            to be registered.
	 * @param time
	 *            , String representation of the time to register.
	 * @return three parameters in the following format: startNr;time\n
	 */
	public String formatResults(String resText, String startNr, String time) {
		String out = "";
		StringBuilder sb = new StringBuilder();		
		String[] startNumbers = startNr.split(",");
		for( int i = 0; i < startNumbers.length; i++ ) {
			startNr = startNumbers[i];
			startNr = startNr.trim();
			out = startNr + ";" + time + "\n";
			sb.append(out);
		}		
		allText = resText + out;
		writeToFile(allText);		
		return sb.toString();
	}
	
	private void writeToFile(String s) {
		FileWriter.writeFile(filePath, allText);
	}
}
